[package]
name = "paxcii"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
term_size = "0.3.2"
clap = "4.0.30"
rodio = { version = "0.16.0", default-features = false, features = ["symphonia-all"] }